pipeline {

    agent any

    environment {
        APP_NAME = "CarRentalManagementSystem"
        SERVER_IP = "13.233.173.60"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build and Deploy') {
            steps {
                sh """
                ssh -o StrictHostKeyChecking=no ubuntu@${SERVER_IP} '
                    sudo rm -rf Car-rental
                    git clone https://github.com/venkat01012004/Car-rental.git
                    cd Car-rental/${APP_NAME}
                    mvn clean package
                   sudo cp target/${APP_NAME}.war /opt/tomcat/webapps/
                '
                """
            }
        }
    }
}
